#!/bin/sh

# Remove any libraries from previous versions

if [[ "x$klogger_uid" == "x" ]]
then
	getent group klogger >/dev/null || groupadd -r klogger 
	getent passwd klogger >/dev/null || useradd -r -g klogger -m -s /bin/bash -c "User for klogger." klogger
else
	getent group klogger >/dev/null || groupadd -g $klogger_uid -r klogger
	getent passwd klogger >/dev/null || useradd -u $klogger_uid -r -g klogger -m -s /bin/bash -c "User for klogger." klogger
fi

if [[ -e "/opt/klogger/lib" ]]
then
	rm /opt/klogger/lib/*
	chown -R klogger.klogger /opt/klogger/lib
fi

if [[ -e "/var/run/klogger" ]]
then
	chown -R klogger.klogger /var/run/klogger
fi 

if [[ -e "/var/log/klogger" ]]
then
	chown -R klogger.klogger /var/log/klogger
fi 

if [[ -e "/opt/klogger/config" ]]
then
	chown -R klogger.klogger /opt/klogger/config
fi